### ISSUE TITLE
Not all services that are listed are free (as in freedom)

### ISSUE THREAD

**Issue by Darin755** [Finalboss77/Best-foss-apps-for-privacy-security-#1]
I noticed that you included proton mail, proton VPN, youtube and Tutanota in your list. These services are not free and should be marked are potencially dangerous.

Everything else looks fine. Nice work

**Comment by Finalboss77** [comment]
Premium plans are help developers to deliver their product without ads and data collection.A developer is also human and as a basic need of all human want monkey do to work.
"Nothing is free in this world" ,if any company is giving u free access to their feature its mean they have their other source of income or may be they are collecting your data and one day project will shut down.So,to support developer i support premium plans and i think there is nothing dangerous about premium plans ,as its on u ,u want to purchase their premium and not.

**Comment by Finalboss77** [comment]
Premium plans are help developers to deliver their product without ads and data collection.A developer is also human and as a basic need of all human want monkey do to work.
"Nothing is free in this world" ,if any company is giving u free access to their feature its mean they have their other source of income or may be they are collecting your data and one day project will shut down.So,to support developer i support premium plans and i think there is nothing dangerous about premium plans ,as its on u ,u want to purchase their premium and not.

And i recommand youtube client app alternative which is Newpipe.

Thanks for reading my list.

**Comment by Darin755** [comment]
I was referring to free as in freedom, not price

**Comment by Darin755** [comment]
Resources:

https://www.fsf.org/about/what-is-free-software

https://www.gnu.org/philosophy/free-sw.html

**Comment by Finalboss77** [comment]
Ohk,but Proton Services are good.
What u use instead of proton services?

**Comment by Finalboss77** [comment]
Ok now i got it,u mean that these projects are not foss.
Ya i know,many apps and services are not foss but overall they are the best alternatives for big tech companies thats why i mentioned them.

**Comment by Darin755** [comment]
I have no issue with you mentioning them but you should include a warning that these services could be unethical.

Here are some good alternatives
https://www.fsf.org/resources/webmail-systems
