### ISSUE TITLE
Add New Inclusions to the List

### ISSUE THREAD

**Issue by ShareASmile** [Finalboss77/Best-foss-apps-for-privacy-security-#2]
Open Source Foss Apps List Complements Following:-

App Manager:
https://github.com/MuntashirAkon/AppManager

Smart Package Manager
https://f-droid.org/packages/com.smartpack.packagemanager/

Music Player offline : Phonograph Plus (as Retro Muic Player has been depricated)
https://github.com/chr56/Phonograph_Plus

Music Player online/offline Youtube Frontend:
https://github.com/z-huang/InnerTune

Downloader: Seal supports downloading from Ytdlp Based 1000 sites
https://github.com/JunkFood02/Seal

Download Manager 
https://github.com/TachibanaGeneralLaboratories/download-navi

Pdf Reader: MJ Pdf Reader based on Pdf Viewer Plus on IzzyOnDroid 
https://gitlab.com/mudlej_android/mj_pdf_reader
https://apt.izzysoft.de/fdroid/index/apk/com.gitlab.mudlej.MjPdfReader

Video Player: Nova Player
https://github.com/nova-video-player/aos-AVP

Sports (Racing): Box Box
https://github.com/BrightDV/BoxBox

File Manger: Material Files
https://github.com/zhanghai/MaterialFiles
Amaze? not sure about its privacy!

Browsers: Fulgris
https://github.com/Slion/Fulguris

SmartCookieWeb based on Firefox (webview based, lite in size)
https://github.com/CookieJarApps/SmartCookieWeb

YouTube Frontend: LibreTube
https://github.com/libre-tube/LibreTube

NewPipe SponsorBlock on IzzyOnDroid repository 
https://github.com/polymorphicshade/NewPipe

Besides All Except MJ Pdf Reader, NewPipe SponsorBlock are available on fdroid app store
Benefit Benefit Benefit

**Comment by Finalboss77** [comment]
Thanks for suggestions🙂

**Comment by ShareASmile** [comment]
Would some of or All of these suggestions would be included?

Just a question.

**Comment by Finalboss77** [comment]
Some of them,as i share my experience here.I only recommand apps and services that i have tried and tested before and get some satifaction.
